package it.gruppostudio.baeejira.model;
// Generated 12-giu-2017 18.26.46 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "mydb", uniqueConstraints = @UniqueConstraint(columnNames = "position"))
public class Status implements java.io.Serializable {

	private Integer id;
	private String name;
	private int position;
	private Set tasks = new HashSet(0);

	public Status() {
	}

	public Status(int position) {
		this.position = position;
	}

	public Status(String name, int position, Set tasks) {
		this.name = name;
		this.position = position;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "position", unique = true, nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set getTasks() {
		return this.tasks;
	}

	public void setTasks(Set tasks) {
		this.tasks = tasks;
	}

}
