package it.gruppostudio.baeejira.model;
// Generated 12-giu-2017 18.26.46 by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaskId generated by hbm2java
 */
@Embeddable
public class TaskId implements java.io.Serializable {

	private int id;
	private int projectId;
	private int statusId;

	public TaskId() {
	}

	public TaskId(int id, int projectId, int statusId) {
		this.id = id;
		this.projectId = projectId;
		this.statusId = statusId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskId))
			return false;
		TaskId castOther = (TaskId) other;

		return (this.getId() == castOther.getId()) && (this.getProjectId() == castOther.getProjectId())
				&& (this.getStatusId() == castOther.getStatusId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getStatusId();
		return result;
	}

}
